# Generated by Django 5.0.3 on 2024-04-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_photo_post_remove_post_published_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
