# Generated by Django 5.0.3 on 2024-04-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_postphoto_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postphoto',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Підписник', 'verbose_name_plural': 'Підписники'},
        ),
    ]
